---
- hosts: all
  become: true
  vars_files:
    - demo.yml
  roles:
    - backup    
  tasks:
    - name: Download war from artifacts and deploy to Tomcat
      maven_artifact:
        group_id: com.mt
        artifact_id: maven-web-application
        extension: war
        version: "{{ version }}"
        repository_url: https://ansibledemo123.jfrog.io/artifactory/AnsibleDemoRelease/
        username: "{{ username }}"
        password: "{{ password }}"
        dest: /opt/apache-tomcat-9.0.70/webapps/
        mode: 777
      notify:
        - restart tomcat
        - name: wait for tomcat to start
          wait_for: port=8080 timeout=60
  handlers:
    - name: Restart tomcat
      service:
        name: tomcat
        state: restarted
